### PR TITLE
add parentId option

### PR DESCRIPTION
**Pull request by PixnBits**
updated README and tests (not in that order ;)

### CODE REVIEW

**Comment by PixnBits** [comment]
Hm. Maybe the node versions need to be updated?
[Looks like](http://docs.travis-ci.com/user/languages/javascript-with-nodejs/) 0.6 is the earliest version now testable, consistent with the error msg of the build: `The command "nvm install 0.4" failed and exited with 2 during .`

**Comment by elisechant** [comment]
@substack can we merge this?

**Comment by substack** [comment]
I think patch does too many things, but I'm open to a patch that only adds the functionality without adding extra unwanted pieces like updating the package.json version.

**Comment by PixnBits** [comment]
I've also since realized it's probably better to use LESS or SASS for going this far down the rabbit hole. This package is great for simple stuff, better to keep it simple, I think.

**Pull request closed without merging**
